-- MySQL Script generated by MySQL Workbench
-- Mon Feb  6 16:41:35 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema JEWELLERY
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema JEWELLERY
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `JEWELLERY` DEFAULT CHARACTER SET utf8 ;
USE `JEWELLERY` ;

-- -----------------------------------------------------
-- Table `JEWELLERY`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JEWELLERY`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `pwd` VARCHAR(45) NOT NULL,
  `role` ENUM('admin', 'user', 'master') NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JEWELLERY`.`basket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JEWELLERY`.`basket` (
  `id_order_buy` INT NOT NULL,
  `id_product` INT NOT NULL,
  `count` INT NOT NULL,
  PRIMARY KEY (`id_order_buy`, `id_product`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JEWELLERY`.`order_buy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JEWELLERY`.`order_buy` (
  `id_order_buy` INT NOT NULL AUTO_INCREMENT,
  `id_product` INT NOT NULL,
  `id_client` INT NOT NULL,
  `price` INT NOT NULL,
  `weight` INT NOT NULL,
  PRIMARY KEY (`id_order_buy`, `id_product`, `id_client`),
  CONSTRAINT `id_OB`
    FOREIGN KEY (`id_order_buy`)
    REFERENCES `JEWELLERY`.`basket` (`id_order_buy`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JEWELLERY`.`order_create`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JEWELLERY`.`order_create` (
  `id_order_create` INT NOT NULL AUTO_INCREMENT,
  `id_client` INT NOT NULL,
  `weight` INT NOT NULL,
  `price` INT NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_order_create`, `id_client`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JEWELLERY`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JEWELLERY`.`clients` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`id_client`),
  CONSTRAINT `id_clients`
    FOREIGN KEY (`id_client`)
    REFERENCES `JEWELLERY`.`order_buy` (`id_client`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_client`
    FOREIGN KEY (`id_client`)
    REFERENCES `JEWELLERY`.`order_create` (`id_client`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JEWELLERY`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JEWELLERY`.`categories` (
  `id_category` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JEWELLERY`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JEWELLERY`.`products` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `id_category` INT NOT NULL,
  `id_type_weaving` INT NOT NULL,
  `name_product` VARCHAR(45) NOT NULL,
  `weight` INT NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`id_product`, `id_category`, `id_type_weaving`),
  INDEX `id_pr_idx` (`id_category` ASC) VISIBLE,
  CONSTRAINT `id_product`
    FOREIGN KEY (`id_product`)
    REFERENCES `JEWELLERY`.`basket` (`id_product`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_prod`
    FOREIGN KEY (`id_product`)
    REFERENCES `JEWELLERY`.`order_buy` (`id_product`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_pr`
    FOREIGN KEY (`id_category`)
    REFERENCES `JEWELLERY`.`categories` (`id_category`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JEWELLERY`.`type_weaving`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JEWELLERY`.`type_weaving` (
  `id_type_weaving` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `image` BLOB NULL,
  PRIMARY KEY (`id_type_weaving`),
  CONSTRAINT `id_TW`
    FOREIGN KEY (`id_type_weaving`)
    REFERENCES `JEWELLERY`.`products` (`id_type_weaving`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
